---

- name: Update cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  tags:
  - system
  - nginx
  - build

- name: Install packages
  package: name={{ item }} state=latest
  with_items: packages
  tags:
  - system
  - nginx
  - build

- name: Nginx main config nginx.conf
  template: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - restart nginx
  tags:
  - config
  - nginx-config
  - build
  - update

- name: Create instance_conf
  copy: src={{ instance_conf_bin }} dest=/{{ instance_conf_bin }} mode=0755 owner=root group=root
  tags:
  - config
  - nginx-config
  - build

- name: enable nginx
  service: name=nginx enabled=yes
  tags:
  - system
  - nginx
  - build
