---

- name: Install packages
  package: name={{ item }} state=latest
  with_items: packages
  notify: enable haproxy
  tags:
  - system
  - haproxy
  - build

- name: haproxy config
  template: src=etc/haproxy/haproxy.cfg dest=/etc/haproxy/haproxy owner=root group=root mode=0755
  tags:
  - system
  - build
  - base
  - config

- name: haproxy startup
  service: name=haproxy state=started enabled=yes
  tags:
  - system
  - build
  - base
  - config
