---

- name: Install packages
  yum: name={{ item }} state=latest
  with_items: packages
  notify: enable tomcat8
  tags:
  - system
  - tomcat8
  - build

- name: copy tomcat8.conf template
  template: src=etc/tomcat8/tomcat8.conf.j2 dest=/etc/tomcat8/tomcat8.conf owner=tomcat group=tomcat mode=0644
  tags:
  - config
  - tomcat8
  - build