---

edda_home: "{{ kenzanmedia_apps }}/edda"
latest_successful_build_url: "http://repo.kenzan-devops.com/nexus/content/repositories/edda/releases/edda/2.0/edda-2.0.war"

# Properties file settings
edda_region: us-east-1
edda_mongo_address: 127.0.0.1:27017
edda_mongo_database: edda
edda_mongo_user:
edda_mongo_password:
edda_elasticsearch_cluster: elasticsearch
edda_elasticsearch_address: 127.0.0.1:9300
edda_elasticsearch_shards: 5
edda_s3current_account:
edda_s3current_table: edda-s3current-collection-index-dev
edda_s3current_bucket: my-bucket
edda_s3current_locationPrefix: edda/s3current/dev
edda_elector_dynamodb_account:
edda_elector_dynamodb_tableName: edda-leader
local_war: edda.war